Refactor to make config less system-specific
Most system-specific stuff should be in ./systems now.
Exception: music directory perhaps

Note that I haven't setup the mechanism for automatically generating
systems for each entry in ./systems yet, as is noted in a comment.